-- MySQL Script generated by MySQL Workbench
-- Sat Feb 10 15:35:14 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema idiots
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema idiots
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `camhell` DEFAULT CHARACTER SET utf8mb4 ;
USE `camhell` ;

-- -----------------------------------------------------
-- Table `camhell`.`camera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camhell`.`camera` (
  `id` VARCHAR(255) NOT NULL,
  `mac` VARCHAR(255) NOT NULL,
  `wifimac` VARCHAR(255) NOT NULL,
  `deviceid` VARCHAR(255) NOT NULL,
  `retry` INT(11) NOT NULL,
  `creation_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `camhell`.`timestamp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camhell`.`timestamp` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1450516
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `camhell`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camhell`.`address` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `camera_id` VARCHAR(255) NOT NULL,
  `date_id` INT(11) NOT NULL,
  `ip` VARCHAR(255) NOT NULL,
  `port` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `address_camera_id` (`camera_id` ASC),
  INDEX `address_date_id` (`date_id` ASC),
  CONSTRAINT `address_ibfk_1`
    FOREIGN KEY (`camera_id`)
    REFERENCES `camhell`.`camera` (`id`),
  CONSTRAINT `address_ibfk_2`
    FOREIGN KEY (`date_id`)
    REFERENCES `camhell`.`timestamp` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 136574
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `camhell`.`credentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camhell`.`credentials` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `camera_id` VARCHAR(255) NOT NULL,
  `date_id` INT(11) NOT NULL,
  `user_admin` VARCHAR(255) NOT NULL,
  `passwd_admin` VARCHAR(255) NOT NULL,
  `user_mod` VARCHAR(255) NOT NULL,
  `passwd_mod` VARCHAR(255) NOT NULL,
  `user_guest` VARCHAR(255) NOT NULL,
  `passwd_guest` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `credentials_camera_id` (`camera_id` ASC),
  INDEX `credentials_date_id` (`date_id` ASC),
  CONSTRAINT `credentials_ibfk_1`
    FOREIGN KEY (`camera_id`)
    REFERENCES `camhell`.`camera` (`id`),
  CONSTRAINT `credentials_ibfk_2`
    FOREIGN KEY (`date_id`)
    REFERENCES `camhell`.`timestamp` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 103479
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `camhell`.`ddns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camhell`.`ddns` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `camera_id` VARCHAR(255) NOT NULL,
  `date_id` INT(11) NOT NULL,
  `service` INT(11) NOT NULL,
  `host` VARCHAR(255) NOT NULL,
  `user` VARCHAR(255) NOT NULL,
  `passwd` VARCHAR(255) NOT NULL,
  `proxy_host` VARCHAR(255) NOT NULL,
  `proxy_port` INT(11) NOT NULL,
  `status` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ddns_camera_id` (`camera_id` ASC),
  INDEX `ddns_date_id` (`date_id` ASC),
  CONSTRAINT `ddns_ibfk_1`
    FOREIGN KEY (`camera_id`)
    REFERENCES `camhell`.`camera` (`id`),
  CONSTRAINT `ddns_ibfk_2`
    FOREIGN KEY (`date_id`)
    REFERENCES `camhell`.`timestamp` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 155000
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `camhell`.`ftp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camhell`.`ftp` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `camera_id` VARCHAR(255) NOT NULL,
  `date_id` INT(11) NOT NULL,
  `host` VARCHAR(255) NOT NULL,
  `port` INT(11) NOT NULL,
  `user` VARCHAR(255) NOT NULL,
  `passwd` VARCHAR(255) NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  `mode` TINYINT(1) NOT NULL,
  `upload_interval` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ftp_camera_id` (`camera_id` ASC),
  INDEX `ftp_date_id` (`date_id` ASC),
  CONSTRAINT `ftp_ibfk_1`
    FOREIGN KEY (`camera_id`)
    REFERENCES `camhell`.`camera` (`id`),
  CONSTRAINT `ftp_ibfk_2`
    FOREIGN KEY (`date_id`)
    REFERENCES `camhell`.`timestamp` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 852795
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `camhell`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camhell`.`location` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `camera_id` VARCHAR(255) NOT NULL,
  `date_id` INT(11) NOT NULL,
  `lat` DOUBLE NULL DEFAULT NULL,
  `lng` DOUBLE NULL DEFAULT NULL,
  `accuracy` DOUBLE NULL DEFAULT NULL,
  `addr_street_number` LONGTEXT NULL DEFAULT NULL,
  `addr_route` LONGTEXT NULL DEFAULT NULL,
  `addr_city` LONGTEXT NULL DEFAULT NULL,
  `addr_region` LONGTEXT NULL DEFAULT NULL,
  `addr_postal_code` LONGTEXT NULL DEFAULT NULL,
  `addr_country` LONGTEXT NOT NULL,
  `addr_formatted` LONGTEXT NULL DEFAULT NULL,
  `detail` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `location_camera_id` (`camera_id` ASC),
  INDEX `location_date_id` (`date_id` ASC),
  CONSTRAINT `location_ibfk_1`
    FOREIGN KEY (`camera_id`)
    REFERENCES `camhell`.`camera` (`id`),
  CONSTRAINT `location_ibfk_2`
    FOREIGN KEY (`date_id`)
    REFERENCES `camhell`.`timestamp` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 115872
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `camhell`.`mail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camhell`.`mail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `camera_id` VARCHAR(255) NOT NULL,
  `date_id` INT(11) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `host` VARCHAR(255) NOT NULL,
  `port` INT(11) NOT NULL,
  `user` VARCHAR(255) NOT NULL,
  `passwd` VARCHAR(255) NOT NULL,
  `ssl` TINYINT(1) NOT NULL,
  `receiver1` VARCHAR(255) NOT NULL,
  `receiver2` VARCHAR(255) NOT NULL,
  `receiver3` VARCHAR(255) NOT NULL,
  `receiver4` VARCHAR(255) NOT NULL,
  `inet_ip` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `mail_camera_id` (`camera_id` ASC),
  INDEX `mail_date_id` (`date_id` ASC),
  CONSTRAINT `mail_ibfk_1`
    FOREIGN KEY (`camera_id`)
    REFERENCES `camhell`.`camera` (`id`),
  CONSTRAINT `mail_ibfk_2`
    FOREIGN KEY (`date_id`)
    REFERENCES `camhell`.`timestamp` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 127148
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `camhell`.`smarteye`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camhell`.`smarteye` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `camera_id` VARCHAR(255) NOT NULL,
  `date_id` INT(11) NOT NULL,
  `enable` TINYINT(1) NOT NULL,
  `domain` VARCHAR(255) NOT NULL,
  `port` INT(11) NOT NULL,
  `user` VARCHAR(255) NOT NULL,
  `passwd` VARCHAR(255) NOT NULL,
  `service` VARCHAR(255) NOT NULL,
  `interval` INT(11) NOT NULL,
  `status` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `smarteye_camera_id` (`camera_id` ASC),
  INDEX `smarteye_date_id` (`date_id` ASC),
  CONSTRAINT `smarteye_ibfk_1`
    FOREIGN KEY (`camera_id`)
    REFERENCES `camhell`.`camera` (`id`),
  CONSTRAINT `smarteye_ibfk_2`
    FOREIGN KEY (`date_id`)
    REFERENCES `camhell`.`timestamp` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11730
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `camhell`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camhell`.`status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `camera_id` VARCHAR(255) NOT NULL,
  `date_id` INT(11) NOT NULL,
  `alias` VARCHAR(255) NOT NULL,
  `sys_ver` VARCHAR(255) NOT NULL,
  `app_ver` VARCHAR(255) NOT NULL,
  `oem_id` VARCHAR(255) NOT NULL,
  `sd_status` INT(11) NOT NULL,
  `syswifi_mode` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `status_camera_id` (`camera_id` ASC),
  INDEX `status_date_id` (`date_id` ASC),
  CONSTRAINT `status_ibfk_1`
    FOREIGN KEY (`camera_id`)
    REFERENCES `camhell`.`camera` (`id`),
  CONSTRAINT `status_ibfk_2`
    FOREIGN KEY (`date_id`)
    REFERENCES `camhell`.`timestamp` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 107994
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `camhell`.`wifi_scan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camhell`.`wifi_scan` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `camera_id` VARCHAR(255) NOT NULL,
  `date_id` INT(11) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `wifi_scan_camera_id` (`camera_id` ASC),
  INDEX `wifi_scan_date_id` (`date_id` ASC),
  CONSTRAINT `wifi_scan_ibfk_1`
    FOREIGN KEY (`camera_id`)
    REFERENCES `camhell`.`camera` (`id`),
  CONSTRAINT `wifi_scan_ibfk_2`
    FOREIGN KEY (`date_id`)
    REFERENCES `camhell`.`timestamp` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1450493
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `camhell`.`wifi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camhell`.`wifi` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `scan_id` INT(11) NOT NULL,
  `ssid` VARCHAR(255) NOT NULL,
  `mac` VARCHAR(255) NOT NULL,
  `mode` TINYINT(1) NOT NULL,
  `security` INT(11) NOT NULL,
  `channel` INT(11) NOT NULL,
  `power` INT(11) NOT NULL,
  `is_ap` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `wifi_scan_id` (`scan_id` ASC),
  CONSTRAINT `wifi_ibfk_1`
    FOREIGN KEY (`scan_id`)
    REFERENCES `camhell`.`wifi_scan` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16248362
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `camhell`.`wifi_ap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camhell`.`wifi_ap` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `scan_id` INT(11) NOT NULL,
  `ssid` VARCHAR(255) NOT NULL,
  `mode` TINYINT(1) NOT NULL,
  `security` INT(11) NOT NULL,
  `wep_encrypt` TINYINT(1) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `password_bits` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `wifi_ap_scan_id` (`scan_id` ASC),
  CONSTRAINT `wifi_ap_ibfk_1`
    FOREIGN KEY (`scan_id`)
    REFERENCES `camhell`.`wifi_scan` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 108990
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
